version: 0.0
Resources:
  - myEKSApp:
      Type: AWS::EKS::Application
      Properties:
        TaskDefinition: ""
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
